### ISSUE TITLE
Callouts are hard to read

### ISSUE THREAD

**Issue by TimMoore** [lightbend/antora-ui-lightbend-theme#14]
Code examples that use long callout text can be hard to read.

For example: https://lightbend.github.io/openshift-deployment-guide/Tutorials/deploying-lagom/configuring-shopping-cart.html#_view_the_configuration_files

<img width="1041" alt="Screen Shot 2019-07-09 at 4 33 33 pm" src="https://user-images.githubusercontent.com/44385/60866630-0246be80-a268-11e9-9e73-01645b7ffcc3.png">

Notes:

- The number label is vertically aligned with the middle, rather than the top, of the associated description. This makes it hard to see where each number starts.
- The line spacing is the same between items as it is within each item, making it hard to see where one item ends and the next begins.

**Comment by rasummer** [comment]
@TimMoore can you point me to the original Ascii Doc source code so that I can reproduce this layout in the UI theme. Thanks

**Comment by TimMoore** [comment]
https://github.com/lightbend/openshift-deployment-guide/blob/antora/modules/deploying-lagom/pages/configuring-shopping-cart.adoc
