### ISSUE TITLE
Highlight in the left-hand-side ToC which section is currently viewed?

### ISSUE THREAD

**Issue by deanwampler** [lightbend/antora-ui-lightbend-theme#19]
This is a feature request. If it's possible to highlight in bold, italic, color, or whatever in the ToC which section is being viewed, or as a compromise, which one was last clicked, that would be helpful for reorienting where you are. 

I find when I'm navigating the draft Platform docs, I want to use the ToC to select the next the items (since the new docs are not all one page, like FDP and Pipelines docs), which means I have to read the ToC and find where I was...

**Comment by rasummer** [comment]
@deanwampler I will see if the platform we are using automatically tags the left TOC with a CSS class that I can style from. If not it will require a custom solution which I will need to assess the effort.  

cc @rstento @TimMoore

**Comment by TimMoore** [comment]
@rasummer looks like it adds the `is-current-page` class

https://github.com/lightbend/antora-ui-lightbend-theme/blob/c4d43699bbf335b26dc2836a51a04356e5ed92ee/src/partials/navigation-tree.hbs#L4

The default theme uses this to bold the selected page:

https://gitlab.com/antora/antora-ui-default/blob/master/src/css/nav.css#L162-165

**Comment by rasummer** [comment]
Thanks @TimMoore, saved me some time. I'll let you know once I've styled.

**Comment by deanwampler** [comment]
woohoo! thanks 👍
