### ISSUE TITLE
Page selector not working for supergroup web-cli

### ISSUE THREAD

**Issue by rstento** [lightbend/antora-ui-lightbend-theme#55]
A few weeks ago when I added the supergroup for Cloudstate for web-cli tabs, it worked. Today it doesn't and I can't figure out why. I've attached the source from a page where I've defined and used them. The tabs appear OK, but there is no selector at the top. When I inspect, the supergroup switch css element is there, but empty:
![image](https://user-images.githubusercontent.com/22889339/83056618-5e026d80-a01b-11ea-8893-a2bcd1dcaeeb.png)

@rasummer, if you could help me figure this out, it would be great. I also realized that it would be better if the group were named supergroup-browser-cli, with tabs named "Browser" and "CLI"  because it seems more user friendly to refer to the app in the browser than as a "web UI". 

Source from the prev page:
= Creating a Cloudstate project
:toc:
:toc-title: ON THIS PAGE
:toclevels: 2
:page-supergroup-web-cli: Interface
include::ROOT:partial$include.adoc[]

A _project_ is a collection of Lightbend Cloudstate services and related items that comprise your application. Cloudstate projects support team collaboration: Multiple people can be members of a single project, and each person can be a member of many projects. 

Cloudstate project names must conform to the following:

- Up to 253 characters
- Can include lowercase letters
- Can include numbers
- Can include hyphen “-” (not underscore”)
- Cannot include spaces

To create a project:

[.tabset]
Web::
+
. Sign into your Cloudstate account.
+ The *My Projects* page opens.
. Click *new project*.
. Enter a  *Project name* following the constraints described above.
. Enter a user-friendly name in the *Project description* field.
. Click *submit*. 
+
Your project should appear in the *My projects* list. A Cloudstate admin will need to activate the project before you can use it. 
CLI::
+
. Log into your Cloudstate account:
+
----
csctl auth login
----
+
The web UI launches in a browser.
+
. Enter your credentials.
+
An authorization page displays.
+
. Click *Authorize*
+
. Create a project by substituting your project name and placing a descriptive name in quotes:
+
----
csctl project new <projectname> “friendly name”
----

At this point, your project is empty, and you are the only person who is a member of it.

== Project status

Along with the project name and description, you will see a project status. This status may begin as `PENDING` until the project has been approved by a Lightbend Cloudstate administrator, at which point it will show as `ACTIVE`, and you can continue using the project to deploy services. 

If your project does not move to `ACTIVE` status in a short time, please email us at mailto:support@lightbend.com[support@lightbend.com] and let us know the project name.

NOTE: You can also use the command line, `csctl project list`, to see a list of all projects you have access to (or have created). See xref:manage-project-adoc[Managing projects] for more information.

== What's next

Next, you will use the command line to xref:auth-kubectl.adoc[authenticate kubectl to your project].

**Comment by rasummer** [comment]
Hi Ruth

I've put some time aside tomorrow to take a look

**Comment by rstento** [comment]
Thanks!
Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by rstento** [comment]
Fixed by #56
