### ISSUE TITLE
Canonical url not generating

### ISSUE THREAD

**Issue by rstento** [lightbend/antora-ui-lightbend-theme#57]
@rasummer, I happened to view source and noticed that the canonical url is not generating in the meta data any more. I tried with both the regular layout and the default_layout: default-lightbend-cloudstate layout.  This isn't the case with the antora-ui-lightbend-cloud-theme. Looking at the published cloudflow.io docs, I see the url metatag.

**Comment by rasummer** [comment]
Canonicals are showing up on the live site, for [example](https://developer.lightbend.com/docs/introduction/streaming-architecture.html)

I think I remember not seeing them locally. Are you only seeing this behavior locally? Do they not show up for cloudflow docs locally?

**Comment by rstento** [comment]
Oh, I'll check.

Ruth Stento
User Experience Lead
Lightbend

512-696-1448
<http://lightbend.com>

**Comment by rstento** [comment]
Indeed, the canonical meta shows after publication. This didn't happen on my machine in the past, but guess I have to get used to it. I'm closing this issue.
