### ISSUE TITLE
Enhancement: Add easy copy to code examples

### ISSUE THREAD

**Issue by rstento** [lightbend/antora-ui-lightbend-theme#64]
It would be nice to have a "clipboard" icon on source code blocks so that readers wouldn't have to select the code manually to copy it. Maybe something like this: https://clipboardjs.com/

**Comment by patriknw** [comment]
@rasummer Much appreciated if you can do something for this? In the Akka Platform Guide there are many many snippets that the user is supposed to copy.

**Comment by rasummer** [comment]
Moved this issue over to the new Antora Theme that is used for latest docs: https://github.com/lightbend/antora-supplemental-ui-lightbend-theme/issues/25
